#include "CsvOutput.h"

#include "Common.h"
#include "Workloads.h"

#include <algorithm>
#include <charconv>
#include <fstream>
#include <map>

#if __has_include("BuildInfo.h")
#include "BuildInfo.h" // generated by GpuSort.vcxproj (target GenerateBuildInfo)
#endif
#ifndef GPUSORT_PACKAGE_COMMIT
#define GPUSORT_PACKAGE_COMMIT "unknown"
#endif

namespace
{
// RFC 4180: quote a field that contains a comma, a quote or a line break; double inner quotes.
std::string Esc(const std::string& s)
{
    if (s.find_first_of(",\"\r\n") == std::string::npos)
        return s;
    std::string r = "\"";
    for (char c : s)
    {
        if (c == '"')
            r += '"';
        r += c;
    }
    return r + "\"";
}

// Fixed-point with '.' as the decimal separator, independent of the C / C++ locale.
std::string Fixed(double v, int precision = 3)
{
    char buf[64];
    const auto res = std::to_chars(buf, buf + sizeof(buf), v, std::chars_format::fixed, precision);
    return res.ec == std::errc() ? std::string(buf, res.ptr) : std::string();
}

std::string Hex4(uint32_t v)
{
    return Format("0x%04X", v);
}

// Algorithm name without its "@suffix" (algorithms.txt names flush-mode variants base@suffix).
std::string BaseName(const std::string& algorithm)
{
    const size_t at = algorithm.find('@');
    return at == std::string::npos ? algorithm : algorithm.substr(0, at);
}

struct IterationSizes
{
    uint32_t largest = 0;
    uint32_t total = 0;
};

// Sizes of measured iterations 0..n-1 per workload (deterministic, see GenerateSizes).
class SizeCache
{
public:
    const std::vector<IterationSizes>& Get(uint32_t workloadId, size_t n)
    {
        std::vector<IterationSizes>& v = m_cache[workloadId];
        for (size_t i = v.size(); i < n; ++i)
            v.push_back(Compute(workloadId, static_cast<uint32_t>(i)));
        return v;
    }

    static IterationSizes Compute(uint32_t workloadId, uint32_t iteration)
    {
        uint32_t sizes[kSortsPerIteration];
        GenerateSizes(workloadId, iteration, sizes);
        IterationSizes r;
        for (uint32_t s : sizes)
        {
            r.largest = std::max(r.largest, s);
            r.total += s;
        }
        return r;
    }

private:
    std::map<uint32_t, std::vector<IterationSizes>> m_cache;
};

class CsvFile
{
public:
    CsvFile(const std::filesystem::path& path) : m_path(path)
    {
        if (path.has_parent_path())
        {
            std::error_code ec;
            std::filesystem::create_directories(path.parent_path(), ec);
        }
        m_out.open(path, std::ios::binary | std::ios::trunc);
    }

    bool Ok() const { return m_out.good(); }

    void Row(const std::vector<std::string>& fields)
    {
        for (size_t i = 0; i < fields.size(); ++i)
        {
            if (i)
                m_buffer += ',';
            m_buffer += Esc(fields[i]);
        }
        m_buffer += "\r\n";
        if (m_buffer.size() >= (1u << 20))
            Flush();
    }

    // Appends an already formatted line (fields escaped, without the line end).
    void RawRow(const std::string& line)
    {
        m_buffer += line;
        m_buffer += "\r\n";
        if (m_buffer.size() >= (1u << 20))
            Flush();
    }

    bool Close(std::string& error)
    {
        Flush();
        m_out.close();
        if (m_out.fail())
        {
            error = "could not write " + m_path.string();
            return false;
        }
        return true;
    }

private:
    void Flush()
    {
        m_out.write(m_buffer.data(), static_cast<std::streamsize>(m_buffer.size()));
        m_buffer.clear();
    }

    std::filesystem::path m_path;
    std::ofstream m_out;
    std::string m_buffer;
};

bool OpenFailed(const CsvFile& f, const std::filesystem::path& path, std::string& error)
{
    if (f.Ok())
        return false;
    error = "could not create " + path.string();
    return true;
}
} // namespace

const char* PackageCommit()
{
    return GPUSORT_PACKAGE_COMMIT;
}

bool WriteResultsCsv(const RunInfo& info, const std::filesystem::path& path, std::string& error)
{
    CsvFile f(path);
    if (OpenFailed(f, path, error))
        return false;
    f.Row({"schema_version", "run_id", "run_timestamp", "computer", "label", "package_commit", "shader_set",
           "gpu_index", "gpu_name", "vendor_id", "device_id", "driver_version", "is_integrated", "dedicated_vram_mb",
           "wave_lane_min", "wave_lane_max", "wave_size", "wave_size_attr", "timestamp_freq_hz", "algorithm",
           "flush_mode", "workload", "sweep_size", "sorts_per_iteration", "iterations", "warmup", "min_us",
           "median_us", "mean_us", "p95_us", "p99_us", "max_us", "stddev_us", "verify_failures",
           "total_elements_per_iter_mean", "algorithm_id", "run_kind", "iterations_requested", "wave_probe_ok",
           "gpu_error", "stable_power", "drain_spin_iters_per_us", "dispatch_info"});

    SizeCache sizeCache;
    for (size_t g = 0; g < info.gpus.size(); ++g)
    {
        const GpuRecord& gpu = info.gpus[g];
        const std::vector<std::string> prefix = {
            std::to_string(kCsvSchemaVersion),
            info.runId,
            info.runTimestamp,
            info.computerName,
            info.label,
            info.packageCommit,
            info.shaderSet,
            std::to_string(g),
            gpu.name,
            Hex4(gpu.vendorId),
            Hex4(gpu.deviceId),
            gpu.driver,
            gpu.uma ? "1" : "0",
            std::to_string(gpu.dedicatedVideoMemory >> 20),
            std::to_string(gpu.waveLaneCountMin),
            std::to_string(gpu.waveLaneCountMax),
            std::to_string(gpu.waveSize),
            gpu.waveSizeAttribute ? "1" : "0",
            std::to_string(gpu.timestampFrequency),
        };
        const std::string probeOk = gpu.waveProbeRows.empty() ? "" : gpu.waveProbeWarning ? "0" : "1";
        const std::string spinRate = gpu.drainSpinCalibrated ? Fixed(gpu.drainSpin.iterationsPerUs, 3) : "";

        for (const auto& c : gpu.combos)
        {
            const std::vector<IterationSizes>& sizes = sizeCache.Get(c.workloadId, c.result.timesUs.size());
            // One row over the given measured iterations (indices into timesUs).
            auto row = [&](const std::string& sweepSize, const std::vector<size_t>& indices, uint32_t failures) {
                std::vector<double> v;
                double elements = 0.0;
                for (size_t i : indices)
                {
                    v.push_back(c.result.timesUs[i]);
                    elements += sizes[i].total;
                }
                std::vector<std::string> fields = prefix;
                fields.push_back(BaseName(c.algorithm));
                fields.push_back(FlushModeName(c.flush));
                fields.push_back(Workloads()[c.workloadId].name);
                fields.push_back(sweepSize);
                fields.push_back(std::to_string(kSortsPerIteration));
                fields.push_back(std::to_string(v.size()));
                fields.push_back(std::to_string(info.warmup));
                if (v.empty())
                {
                    for (int k = 0; k < 7; ++k)
                        fields.emplace_back();
                }
                else
                {
                    const Stats st = ComputeStats(v);
                    for (double x : {st.min, st.median, st.mean, st.p95, st.p99, st.max, st.stddev})
                        fields.push_back(Fixed(x));
                }
                fields.push_back(std::to_string(failures));
                fields.push_back(v.empty() ? std::string() : Fixed(elements / static_cast<double>(v.size()), 1));
                fields.push_back(c.algorithm);
                fields.push_back(info.runKind);
                fields.push_back(std::to_string(info.iterations));
                fields.push_back(probeOk);
                fields.push_back(gpu.error);
                fields.push_back(gpu.stablePower);
                fields.push_back(spinRate);
                const auto di = gpu.dispatchInfo.find(c.algorithm);
                fields.push_back(di == gpu.dispatchInfo.end() ? std::string() : di->second);
                f.Row(fields);
            };

            if (!IsSweepWorkload(c.workloadId))
            {
                std::vector<size_t> all(c.result.timesUs.size());
                for (size_t i = 0; i < all.size(); ++i)
                    all[i] = i;
                row("", all, c.result.failures);
                continue;
            }
            // Sweep: one row per sort size (every sort of an iteration has that size). The
            // verification failures are split by the size of the failing iteration (warmup included).
            std::map<uint32_t, std::vector<size_t>> bySize;
            for (size_t i = 0; i < c.result.timesUs.size(); ++i)
                bySize[sizes[i].largest].push_back(i);
            std::map<uint32_t, uint32_t> failuresBySize;
            for (uint32_t it : c.result.failedIterations)
                ++failuresBySize[SizeCache::Compute(c.workloadId, it).largest];
            if (bySize.empty())
            {
                row("", {}, c.result.failures);
                continue;
            }
            for (const auto& [size, indices] : bySize)
                row(std::to_string(size), indices, failuresBySize[size]);
        }
    }
    return f.Close(error);
}

bool WriteSamplesCsv(const RunInfo& info, const std::filesystem::path& path, std::string& error)
{
    CsvFile f(path);
    if (OpenFailed(f, path, error))
        return false;
    f.Row({"run_id", "gpu_index", "wave_size", "algorithm", "flush_mode", "workload", "iteration", "time_us",
           "largest_sort", "total_elements", "sweep_size"});
    SizeCache sizeCache;
    for (size_t g = 0; g < info.gpus.size(); ++g)
    {
        const GpuRecord& gpu = info.gpus[g];
        for (const auto& c : gpu.combos)
        {
            const bool sweep = IsSweepWorkload(c.workloadId);
            const std::vector<IterationSizes>& sizes = sizeCache.Get(c.workloadId, c.result.timesUs.size());
            // Key fields, escaped once per combo.
            const std::string key = Esc(info.runId) + "," + std::to_string(g) + "," + std::to_string(gpu.waveSize) +
                                    "," + Esc(BaseName(c.algorithm)) + "," + FlushModeName(c.flush) + "," +
                                    Workloads()[c.workloadId].name + ",";
            for (size_t i = 0; i < c.result.timesUs.size(); ++i)
            {
                std::string line = key;
                line += std::to_string(i);
                line += ',';
                line += Fixed(c.result.timesUs[i]);
                line += ',';
                line += std::to_string(sizes[i].largest);
                line += ',';
                line += std::to_string(sizes[i].total);
                line += ',';
                if (sweep)
                    line += std::to_string(sizes[i].largest);
                f.RawRow(line);
            }
        }
    }
    return f.Close(error);
}

bool WriteWaveProbeCsv(const RunInfo& info, const std::filesystem::path& path, std::string& error)
{
    CsvFile f(path);
    if (OpenFailed(f, path, error))
        return false;
    std::vector<std::string> header = {
        "schema_version", "run_id",         "run_timestamp",  "computer",      "label",         "package_commit",
        "run_kind",       "gpu_index",      "gpu_name",       "vendor_id",     "device_id",     "driver_version",
        "is_integrated",  "wave_lane_min",  "wave_lane_max",  "wave_size",     "wave_size_attr", "probe_variant",
        "probe_wave_size", "sort_config",   "group_sizes",    "observed_lanes", "verdict",      "problem"};
    for (const auto& t : WaveProbeTestColumns())
        header.push_back(t);
    header.push_back("gpu_error");
    f.Row(header);
    for (size_t g = 0; g < info.gpus.size(); ++g)
    {
        const GpuRecord& gpu = info.gpus[g];
        for (const auto& r : gpu.waveProbeRows)
        {
            std::vector<std::string> fields = {std::to_string(kCsvSchemaVersion),
                                               info.runId,
                                               info.runTimestamp,
                                               info.computerName,
                                               info.label,
                                               info.packageCommit,
                                               info.runKind,
                                               std::to_string(g),
                                               gpu.name,
                                               Hex4(gpu.vendorId),
                                               Hex4(gpu.deviceId),
                                               gpu.driver,
                                               gpu.uma ? "1" : "0",
                                               std::to_string(gpu.waveLaneCountMin),
                                               std::to_string(gpu.waveLaneCountMax),
                                               std::to_string(gpu.waveSize),
                                               gpu.waveSizeAttribute ? "1" : "0",
                                               r.variant,
                                               std::to_string(r.attributeSize),
                                               r.sortConfig ? "1" : "0",
                                               r.groupSizes,
                                               r.observedLanes,
                                               r.verdict,
                                               r.problem};
            for (const auto& t : r.tests)
                fields.push_back(t);
            fields.push_back(gpu.error);
            f.Row(fields);
        }
    }
    return f.Close(error);
}
